db.define_table( 'dform_validationform1',
   Field( 'f0', 'string', label= 'f0', default= 'w2p f0' ), 
   Field( 'f1', 'string', label= 'f1', default= 'w2p f1' ), 
   Field( 'f2', 'string', label= 'f2', default= 'w2p f2' ), 
   Field( 'f3', 'string', label= 'f3', default= 'w2p f3' ), 
   Field( 'f4', 'string', label= 'f4', default= 'w2p f4' ), 
   Field( 'f5', 'string', label= 'f5', default= 'w2p f5' ), 
   Field( 'f6', 'string', label= 'f6', default= 'w2p f6' ), 
   Field( 'f7', 'string', label= 'f7', default= 'w2p f7' ), 
   Field( 'f8', 'string', label= 'f8', default= 'w2p f8' ), 
   Field( 'f9', 'string', label= 'f9', default= 'w2p f9' ), 
   Field( 'f10', 'string', label= 'f10', default= 'w2p f10' ), 
   Field( 'f11', requires=IS_IN_SET( ['l1-741','l1-742','l1-743'] ), default= 'l1-742' ),
   Field( 'f12', requires=IS_IN_SET( ['l1-744','l1-745','l1-746'] ), default= 'l1-745' ),
   )