db.define_table( 'dform_generalform3',
   Field( 'f0', 'boolean', label= 'f0' , default= True), 
   Field( 'f1', 'boolean', label= 'f1' , default= True), 
   Field( 'f2', 'boolean', label= 'f2' , default= True), 
   Field( 'f3', 'boolean', label= 'f3' , default= True), 
   Field( 'f4', requires=IS_IN_SET(['l1-844', 'l1-845', ]), default= 'l1-844', widget=SQLFORM.widgets.radio.widget),
   Field( 'f5', requires=IS_IN_SET(['l1-847', 'l1-848', ]), default= 'l1-847', widget=SQLFORM.widgets.radio.widget),
   Field( 'f6', requires=IS_IN_SET(['l1-850', 'l1-851', ]), default= 'l1-850', widget=SQLFORM.widgets.radio.widget),
   Field( 'f7', requires=IS_IN_SET(['l1-853', 'l1-854', ]), default= 'l1-853', widget=SQLFORM.widgets.radio.widget),
   Field( 'f8', 'boolean', label= 'f8' , default= True), 
   Field( 'f9', 'boolean', label= 'f9' , default= True), 
   Field( 'f10', 'boolean', label= 'f10' , default= True), 
   Field( 'f11', 'boolean', label= 'f11' , default= True), 
   Field( 'f12', 'boolean', label= 'f12' , default= True), 
   Field( 'f13', 'boolean', label= 'f13' , default= True), 
   Field( 'f14', 'boolean', label= 'f14' , default= True), 
   Field( 'f15', 'boolean', label= 'f15' , default= True), 
   Field( 'f16', 'boolean', label= 'f16' , default= True), 
   Field( 'f17', 'boolean', label= 'f17' , default= True), 
   Field( 'f18', 'boolean', label= 'f18' , default= True), 
   Field( 'f19', 'boolean', label= 'f19' , default= True), 
   Field( 'f20', 'boolean', label= 'f20' , default= True), 
   )