#
# table for controller: tabs
#

from gluon.contrib.populate import populate

db.define_table('dtabs', 
     Field('f0', label='key',  writable = True , length= 1000),
     Field('f1', 'text',  label='data string', length= 1000),
     Field('f2', 'text', label='save data string', length= 1000, default='' ),
     )
#

if not db(db.dtabs.id ).count():
    db.dtabs.insert( f0= 'sp753', f1= '(753)outdated')
    db.dtabs.insert( f0= 'pc754', f1= '(754)to improve your experience.')
    db.dtabs.insert( f0= 'aa755', f1= '(755)upgrade your browser')
    db.dtabs.insert( f0= 'hh757', f1= '(757)Messages')
    db.dtabs.insert( f0= 'hh759', f1= '(759)David Belle')
    db.dtabs.insert( f0= 'pa760', f1= '(760)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh762', f1= '(762)Jonathan Morris')
    db.dtabs.insert( f0= 'pa763', f1= '(763)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh765', f1= '(765)Fredric Mitchell')
    db.dtabs.insert( f0= 'pa766', f1= '(766)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh768', f1= '(768)David Belle')
    db.dtabs.insert( f0= 'pa769', f1= '(769)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh771', f1= '(771)Glenn Jecobs')
    db.dtabs.insert( f0= 'pa772', f1= '(772)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'aa773', f1= '(773)View All')
    db.dtabs.insert( f0= 'hh774', f1= '(774)Notification')
    db.dtabs.insert( f0= 'hh776', f1= '(776)David Belle')
    db.dtabs.insert( f0= 'pa777', f1= '(777)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh779', f1= '(779)Jonathan Morris')
    db.dtabs.insert( f0= 'pa780', f1= '(780)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh782', f1= '(782)Fredric Mitchell')
    db.dtabs.insert( f0= 'pa783', f1= '(783)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh785', f1= '(785)David Belle')
    db.dtabs.insert( f0= 'pa786', f1= '(786)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'hh788', f1= '(788)Glenn Jecobs')
    db.dtabs.insert( f0= 'pa789', f1= '(789)Cum sociis natoque penatibus et magnis dis parturient montes')
    db.dtabs.insert( f0= 'aa790', f1= '(790)View All')
    db.dtabs.insert( f0= 'hh791', f1= '(791)Tasks')
    db.dtabs.insert( f0= 'pa792', f1= '(792)HTML5 Validation Report')
    db.dtabs.insert( f0= 'sp793', f1= '(793)95%')
    db.dtabs.insert( f0= 'pa794', f1= '(794)Google Chrome Extension')
    db.dtabs.insert( f0= 'sp795', f1= '(795)85%')
    db.dtabs.insert( f0= 'pa796', f1= '(796)Social Internet Projects')
    db.dtabs.insert( f0= 'sp797', f1= '(797)93%')
    db.dtabs.insert( f0= 'pa798', f1= '(798)Bootstrap Admin Template')
    db.dtabs.insert( f0= 'sp799', f1= '(799)93%')
    db.dtabs.insert( f0= 'pa800', f1= '(800)Youtube Client App')
    db.dtabs.insert( f0= 'sp801', f1= '(801)93%')
    db.dtabs.insert( f0= 'aa802', f1= '(802)View All')
    db.dtabs.insert( f0= 'hh803', f1= '(803)Chat')
    db.dtabs.insert( f0= 'pb804', f1= '(804)Search People')
    db.dtabs.insert( f0= 'hh806', f1= '(806)David Belle')
    db.dtabs.insert( f0= 'pa807', f1= '(807)Available')
    db.dtabs.insert( f0= 'hh809', f1= '(809)Jonathan Morris')
    db.dtabs.insert( f0= 'pa810', f1= '(810)Last seen 3 hours ago')
    db.dtabs.insert( f0= 'hh812', f1= '(812)Fredric Mitchell')
    db.dtabs.insert( f0= 'pa813', f1= '(813)Last seen 2 minutes ago')
    db.dtabs.insert( f0= 'hh815', f1= '(815)David Belle')
    db.dtabs.insert( f0= 'pa816', f1= '(816)Available')
    db.dtabs.insert( f0= 'hh818', f1= '(818)Glenn Jecobs')
    db.dtabs.insert( f0= 'pa819', f1= '(819)Available')
    db.dtabs.insert( f0= 'aa820', f1= '(820)View All')
    db.dtabs.insert( f0= 'aa821', f1= '(821)Home')
    db.dtabs.insert( f0= 'aa823', f1= '(823)Dashboard One')
    db.dtabs.insert( f0= 'aa825', f1= '(825)Dashboard Two')
    db.dtabs.insert( f0= 'aa827', f1= '(827)Dashboard Three')
    db.dtabs.insert( f0= 'aa829', f1= '(829)Dashboard Four')
    db.dtabs.insert( f0= 'aa831', f1= '(831)Analytics')
    db.dtabs.insert( f0= 'aa833', f1= '(833)Widgets')
    db.dtabs.insert( f0= 'aa834', f1= '(834)Email')
    db.dtabs.insert( f0= 'aa836', f1= '(836)Inbox')
    db.dtabs.insert( f0= 'aa838', f1= '(838)View Email')
    db.dtabs.insert( f0= 'aa840', f1= '(840)Compose Email')
    db.dtabs.insert( f0= 'aa841', f1= '(841)Interface')
    db.dtabs.insert( f0= 'aa843', f1= '(843)Animations')
    db.dtabs.insert( f0= 'aa845', f1= '(845)Google Map')
    db.dtabs.insert( f0= 'aa847', f1= '(847)Data Maps')
    db.dtabs.insert( f0= 'aa849', f1= '(849)Code Editor')
    db.dtabs.insert( f0= 'aa851', f1= '(851)Images Cropper')
    db.dtabs.insert( f0= 'aa853', f1= '(853)Wizard')
    db.dtabs.insert( f0= 'aa854', f1= '(854)Charts')
    db.dtabs.insert( f0= 'aa856', f1= '(856)Flot Charts')
    db.dtabs.insert( f0= 'aa858', f1= '(858)Bar Charts')
    db.dtabs.insert( f0= 'aa860', f1= '(860)Line Charts')
    db.dtabs.insert( f0= 'aa862', f1= '(862)Area Charts')
    db.dtabs.insert( f0= 'aa863', f1= '(863)Tables')
    db.dtabs.insert( f0= 'aa865', f1= '(865)Normal Table')
    db.dtabs.insert( f0= 'aa867', f1= '(867)Data Table')
    db.dtabs.insert( f0= 'aa868', f1= '(868)Forms')
    db.dtabs.insert( f0= 'aa870', f1= '(870)Form Elements')
    db.dtabs.insert( f0= 'aa872', f1= '(872)Form Components')
    db.dtabs.insert( f0= 'aa874', f1= '(874)Form Examples')
    db.dtabs.insert( f0= 'aa875', f1= '(875)App views')
    db.dtabs.insert( f0= 'aa877', f1= '(877)Notifications')
    db.dtabs.insert( f0= 'aa879', f1= '(879)Alerts')
    db.dtabs.insert( f0= 'aa881', f1= '(881)Modals')
    db.dtabs.insert( f0= 'aa883', f1= '(883)Buttons')
    db.dtabs.insert( f0= 'aa885', f1= '(885)Tabs')
    db.dtabs.insert( f0= 'aa887', f1= '(887)Accordion')
    db.dtabs.insert( f0= 'aa889', f1= '(889)Dialogs')
    db.dtabs.insert( f0= 'aa891', f1= '(891)Popovers')
    db.dtabs.insert( f0= 'aa893', f1= '(893)Tooltips')
    db.dtabs.insert( f0= 'aa895', f1= '(895)Dropdowns')
    db.dtabs.insert( f0= 'aa896', f1= '(896)Pages')
    db.dtabs.insert( f0= 'aa898', f1= '(898)Contact')
    db.dtabs.insert( f0= 'aa900', f1= '(900)Invoice')
    db.dtabs.insert( f0= 'aa902', f1= '(902)Typography')
    db.dtabs.insert( f0= 'aa904', f1= '(904)Color')
    db.dtabs.insert( f0= 'aa906', f1= '(906)Login Register')
    db.dtabs.insert( f0= 'aa908', f1= '(908)404 Page')
    db.dtabs.insert( f0= 'aa910', f1= '(910)Dashboard One')
    db.dtabs.insert( f0= 'aa912', f1= '(912)Dashboard Two')
    db.dtabs.insert( f0= 'aa914', f1= '(914)Dashboard Three')
    db.dtabs.insert( f0= 'aa916', f1= '(916)Dashboard Four')
    db.dtabs.insert( f0= 'aa918', f1= '(918)Analytics')
    db.dtabs.insert( f0= 'aa920', f1= '(920)Widgets')
    db.dtabs.insert( f0= 'aa922', f1= '(922)Inbox')
    db.dtabs.insert( f0= 'aa924', f1= '(924)View Email')
    db.dtabs.insert( f0= 'aa926', f1= '(926)Compose Email')
    db.dtabs.insert( f0= 'aa928', f1= '(928)Animations')
    db.dtabs.insert( f0= 'aa930', f1= '(930)Google Map')
    db.dtabs.insert( f0= 'aa932', f1= '(932)Data Maps')
    db.dtabs.insert( f0= 'aa934', f1= '(934)Code Editor')
    db.dtabs.insert( f0= 'aa936', f1= '(936)Images Cropper')
    db.dtabs.insert( f0= 'aa938', f1= '(938)Wizard')
    db.dtabs.insert( f0= 'aa940', f1= '(940)Flot Charts')
    db.dtabs.insert( f0= 'aa942', f1= '(942)Bar Charts')
    db.dtabs.insert( f0= 'aa944', f1= '(944)Line Charts')
    db.dtabs.insert( f0= 'aa946', f1= '(946)Area Charts')
    db.dtabs.insert( f0= 'aa948', f1= '(948)Normal Table')
    db.dtabs.insert( f0= 'aa950', f1= '(950)Data Table')
    db.dtabs.insert( f0= 'aa952', f1= '(952)Form Elements')
    db.dtabs.insert( f0= 'aa954', f1= '(954)Form Components')
    db.dtabs.insert( f0= 'aa956', f1= '(956)Form Examples')
    db.dtabs.insert( f0= 'aa958', f1= '(958)Notifications')
    db.dtabs.insert( f0= 'aa960', f1= '(960)Alerts')
    db.dtabs.insert( f0= 'aa962', f1= '(962)Modals')
    db.dtabs.insert( f0= 'aa964', f1= '(964)Buttons')
    db.dtabs.insert( f0= 'aa966', f1= '(966)Tabs')
    db.dtabs.insert( f0= 'aa968', f1= '(968)Accordion')
    db.dtabs.insert( f0= 'aa970', f1= '(970)Dialogs')
    db.dtabs.insert( f0= 'aa972', f1= '(972)Popovers')
    db.dtabs.insert( f0= 'aa974', f1= '(974)Tooltips')
    db.dtabs.insert( f0= 'aa976', f1= '(976)Dropdowns')
    db.dtabs.insert( f0= 'aa978', f1= '(978)Contact')
    db.dtabs.insert( f0= 'aa980', f1= '(980)Invoice')
    db.dtabs.insert( f0= 'aa982', f1= '(982)Typography')
    db.dtabs.insert( f0= 'aa984', f1= '(984)Color')
    db.dtabs.insert( f0= 'aa986', f1= '(986)Login Register')
    db.dtabs.insert( f0= 'aa988', f1= '(988)404 Page')
    db.dtabs.insert( f0= 'hh989', f1= '(989)Tabs')
    db.dtabs.insert( f0= 'sx990', f1= '(990)Admin Template')
    db.dtabs.insert( f0= 'pf991', f1= '(991)Welcome to Notika')
    db.dtabs.insert( f0= 'hh992', f1= '(992)Tabs')
    db.dtabs.insert( f0= 'pa993', f1= '(993)Add quick, dynamic tab functionality to transition through panes of local content, even via dropdown menus.')
    db.dtabs.insert( f0= 'aa994', f1= '(994)Tab Menu 1')
    db.dtabs.insert( f0= 'aa995', f1= '(995)Tab Menu 2')
    db.dtabs.insert( f0= 'aa996', f1= '(996)Tab Menu 3')
    db.dtabs.insert( f0= 'pc997', f1= '(997)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'pc998', f1= '(998)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'pc999', f1= '(999)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'hh1000', f1= '(1000)Tabs Right Aligned')
    db.dtabs.insert( f0= 'pc1001', f1= '(1001)to align the tab header to right side.')
    db.dtabs.insert( f0= 'pf1002', f1= '(1002)Simply include the class')
    db.dtabs.insert( f0= 'aa1003', f1= '(1003)Tab Menu 1')
    db.dtabs.insert( f0= 'aa1004', f1= '(1004)Tab Menu 2')
    db.dtabs.insert( f0= 'aa1005', f1= '(1005)Tab Menu 3')
    db.dtabs.insert( f0= 'pc1006', f1= '(1006)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'pc1007', f1= '(1007)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'pc1008', f1= '(1008)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuadan of pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massa imperdiet quam. Pellentesque commodo eros a enim. Vestibulum ante ipsum primis in faucibus orci the luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Phasellus a est. Pellentesque commodo eros a enim. Cras ultricies mi eu turpis hendrerit of fringilla. Donec mollis hendrerit risus. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Praesent egestas neque eu enim. In hac habitasse plat.')
    db.dtabs.insert( f0= 'hh1009', f1= '(1009)Tabs With animations')
    db.dtabs.insert( f0= 'pf1010', f1= '(1010)You may add optional animation classes to animate the tab panes when switching. Please refer the Animations page to get all the available classes')
    db.dtabs.insert( f0= 'aa1011', f1= '(1011)Click Here')
    db.dtabs.insert( f0= 'aa1012', f1= '(1012)Tab Menu 1')
    db.dtabs.insert( f0= 'aa1013', f1= '(1013)Tab Menu 2')
    db.dtabs.insert( f0= 'aa1014', f1= '(1014)Tab Menu 3')
    db.dtabs.insert( f0= 'pc1015', f1= '(1015)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.dtabs.insert( f0= 'pc1016', f1= '(1016)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.dtabs.insert( f0= 'pc1017', f1= '(1017)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.dtabs.insert( f0= 'aa1018', f1= '(1018)Tab Menu 1')
    db.dtabs.insert( f0= 'aa1019', f1= '(1019)Tab Menu 2')
    db.dtabs.insert( f0= 'aa1020', f1= '(1020)Tab Menu 3')
    db.dtabs.insert( f0= 'pc1021', f1= '(1021)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.dtabs.insert( f0= 'pc1022', f1= '(1022)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.dtabs.insert( f0= 'pc1023', f1= '(1023)In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nam eget dui. In ac felis quis tortor malesuada pretium. Phasellus consectetuer vestibulum elit. Duis lobortis massantesan imperdiet quam. Pellentesque commodo eros a enim.')
    db.commit()
#
