#
# table for controller: review
#

from gluon.contrib.populate import populate

db.define_table('dreview', 
     Field('f0', label='key',  writable = True , length= 1000),
     Field('f1', 'text',  label='data string', length= 1000),
     Field('f2', 'text', label='save data string', length= 1000, default='' ),
     )
#

if not db(db.dreview.id ).count():
    db.dreview.insert( f0= 'aa11', f1= '(11)Login')
    db.dreview.insert( f0= 'aa13', f1= '(13)Home')
    db.dreview.insert( f0= 'aa15', f1= '(15)Games')
    db.dreview.insert( f0= 'aa17', f1= '(17)Blog')
    db.dreview.insert( f0= 'aa19', f1= '(19)Forums')
    db.dreview.insert( f0= 'aa21', f1= '(21)Contact')
    db.dreview.insert( f0= 'di22', f1= '(22)Latest News')
    db.dreview.insert( f0= 'sx23', f1= '(23)new')
    db.dreview.insert( f0= 'sx24', f1= '(24)strategy')
    db.dreview.insert( f0= 'sx25', f1= '(25)racing')
    db.dreview.insert( f0= 'hh27', f1= '(27)Game reviews')
    db.dreview.insert( f0= 'pa28', f1= '(28)Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum.')
    db.dreview.insert( f0= 'di30', f1= '(30)9.3')
    db.dreview.insert( f0= 'hh31', f1= '(31)Overwatch Halloween')
    db.dreview.insert( f0= 'pa32', f1= '(32)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di34', f1= '(34)9.3')
    db.dreview.insert( f0= 'hh35', f1= '(35)Grand Theft Auto')
    db.dreview.insert( f0= 'pa36', f1= '(36)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di38', f1= '(38)9.3')
    db.dreview.insert( f0= 'hh39', f1= '(39)Avatar')
    db.dreview.insert( f0= 'pa40', f1= '(40)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di42', f1= '(42)9.3')
    db.dreview.insert( f0= 'hh43', f1= '(43)Anthem')
    db.dreview.insert( f0= 'pa44', f1= '(44)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di46', f1= '(46)9.3')
    db.dreview.insert( f0= 'hh47', f1= '(47)Cyberpunk 2077')
    db.dreview.insert( f0= 'pa48', f1= '(48)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di50', f1= '(50)9.3')
    db.dreview.insert( f0= 'hh51', f1= '(51)Spiderman')
    db.dreview.insert( f0= 'pa52', f1= '(52)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame. Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'bu53', f1= '(53)Load More')
    db.dreview.insert( f0= 'di55', f1= '(55)new')
    db.dreview.insert( f0= 'hh56', f1= '(56)Recent Reviews')
    db.dreview.insert( f0= 'di58', f1= '(58)9.3')
    db.dreview.insert( f0= 'hh59', f1= '(59)Assasins Creed')
    db.dreview.insert( f0= 'pa60', f1= '(60)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di62', f1= '(62)9.5')
    db.dreview.insert( f0= 'hh63', f1= '(63)Doom')
    db.dreview.insert( f0= 'pa64', f1= '(64)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di66', f1= '(66)9.1')
    db.dreview.insert( f0= 'hh67', f1= '(67)Overwatch')
    db.dreview.insert( f0= 'pa68', f1= '(68)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'di70', f1= '(70)9.7')
    db.dreview.insert( f0= 'hh71', f1= '(71)GTA')
    db.dreview.insert( f0= 'pa72', f1= '(72)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'pa75', f1= '(75)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum dolor sit ame.')
    db.dreview.insert( f0= 'hd76', f1= '(76)Latest Posts')
    db.dreview.insert( f0= 'di78', f1= '(78)June 21, 2018')
    db.dreview.insert( f0= 'pa79', f1= '(79)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum')
    db.dreview.insert( f0= 'aa80', f1= '(80)By Admin')
    db.dreview.insert( f0= 'di82', f1= '(82)June 21, 2018')
    db.dreview.insert( f0= 'pa83', f1= '(83)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum')
    db.dreview.insert( f0= 'aa84', f1= '(84)By Admin')
    db.dreview.insert( f0= 'di86', f1= '(86)June 21, 2018')
    db.dreview.insert( f0= 'pa87', f1= '(87)Lorem ipsum dolor sit amet, consectetur adipisc ing ipsum')
    db.dreview.insert( f0= 'aa88', f1= '(88)By Admin')
    db.dreview.insert( f0= 'hd89', f1= '(89)Top Comments')
    db.dreview.insert( f0= 'sp91', f1= '(91)on')
    db.dreview.insert( f0= 'pc92', f1= '(92)Lorem ipsum dolor sit amet, co')
    db.dreview.insert( f0= 'aa93', f1= '(93)James Smith')
    db.dreview.insert( f0= 'di94', f1= '(94)June 21, 2018')
    db.dreview.insert( f0= 'sp96', f1= '(96)on')
    db.dreview.insert( f0= 'pc97', f1= '(97)Lorem ipsum dolor sit amet, co')
    db.dreview.insert( f0= 'aa98', f1= '(98)James Smith')
    db.dreview.insert( f0= 'di99', f1= '(99)June 21, 2018')
    db.dreview.insert( f0= 'sp101', f1= '(101)on')
    db.dreview.insert( f0= 'pc102', f1= '(102)Lorem ipsum dolor sit amet, co')
    db.dreview.insert( f0= 'aa103', f1= '(103)James Smith')
    db.dreview.insert( f0= 'di104', f1= '(104)June 21, 2018')
    db.dreview.insert( f0= 'sp106', f1= '(106)on')
    db.dreview.insert( f0= 'pc107', f1= '(107)Lorem ipsum dolor sit amet, co')
    db.dreview.insert( f0= 'aa108', f1= '(108)James Smith')
    db.dreview.insert( f0= 'di109', f1= '(109)June 21, 2018')
    db.dreview.insert( f0= 'aa111', f1= '(111)Home')
    db.dreview.insert( f0= 'aa113', f1= '(113)Games')
    db.dreview.insert( f0= 'aa115', f1= '(115)Blog')
    db.dreview.insert( f0= 'aa117', f1= '(117)Forums')
    db.dreview.insert( f0= 'aa119', f1= '(119)Contact')
    db.commit()
#
